Mkdocs for the documentation
krr-up/python-project-template pull request #49
Opened 2024-12-03 22:46 UTC by susuhahnml

2024-12-03 23:19 UTC, rkaminsk requested changes
Just one small thing. I'll also give it a test run tomorrow.

2024-12-03 23:19 UTC, rkaminsk commented on noxfile.py
> +    session.run("open", "http://127.0.0.1:8000/systems/fillname/")
Can we handle this as before again? Maybe have a way to just build the documentation and one to serve it?
To build:
```
nox -s doc
```
To also serve:
```
nox -s doc serve
```
The docstring also has to be adjusted.

2024-12-04 10:09 UTC, sthiele commented
@susuhahnml Could we change the directory `/docs/reference/api` to `/docs/reference/API` to get the capitalization right?

2024-12-04 12:47 UTC, rkaminsk commented
> @susuhahnml Could we change the directory `/docs/reference/api` to `/docs/reference/API` to get the capitalization right?

Please lets stick to all lower case.

2024-12-04 13:02 UTC, sthiele commented
> Please lets stick to all lower case for filenames and urls.

Could one use the nav section in the mkdocs.yml file?

2024-12-04 15:09 UTC, rkaminsk commented
I had a look regarding the navigation. It seems like mkdocs uses the filename to generate navitems and there is no way around except specifying the navigation in the mkdocs.yml or using plugins:

We could, for example, use <https://pypi.org/project/mkdocs-gen-nav-plugin/>.

2024-12-04 15:11 UTC, rkaminsk commented
Another problem is that the yaml page preambles are currently rendered as markdown. In my tests, mkdocs seems to parse multimarkdown preambles. Maybe this is the default? We should decide what to use here.

2024-12-04 19:29 UTC, rkaminsk commented
One last thing, the blue bar on top in dark mode looks kinda ugly.

2024-12-04 23:19 UTC, susuhahnml commented
I was running away a bit from explicitly writing the navigation so that adding a file was enough and one less step. But I am also ok with keeping it as it gives us more flexibility. Regarding the color, we could use one of the default ones but I would also like to have something unique, since the default is used by many other systems. I also agree it does not look amazing in dark mode.

2024-12-04 23:32 UTC, susuhahnml commented
I changed the color slightly, let me know if you like it better, I imagine that with the whole new branding we would ideally use whatever color is decided there. I also updated the readme with the -- serve for the docs

2024-12-05 09:02 UTC, rkaminsk approved these changes

2024-12-05 14:50 UTC, merged